// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/data/chains": {
            "get": {
                "description": "Get a paginated list of blockchains across all subnets",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - Subnets"
                ],
                "summary": "List chains",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by subnet ID",
                        "name": "subnet_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.SubnetChain"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/evm/{chainId}/address/{address}/txs": {
            "get": {
                "description": "Get transactions sent from or to a specific address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - EVM"
                ],
                "summary": "Get transactions by address",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Wallet address (0x-prefixed)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Transaction"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/evm/{chainId}/blocks": {
            "get": {
                "description": "Get a paginated list of blocks for a specific chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - EVM"
                ],
                "summary": "List blocks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID (e.g., 43114 for C-Chain)",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Block"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/evm/{chainId}/blocks/{number}": {
            "get": {
                "description": "Get details for a specific block including transaction count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - EVM"
                ],
                "summary": "Get block by number",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Block number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.Block"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/evm/{chainId}/txs": {
            "get": {
                "description": "Get a paginated list of transactions for a specific chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - EVM"
                ],
                "summary": "List transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Transaction"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/evm/{chainId}/txs/{hash}": {
            "get": {
                "description": "Get details for a specific transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - EVM"
                ],
                "summary": "Get transaction by hash",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transaction hash (0x-prefixed)",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.Transaction"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/l1s": {
            "get": {
                "description": "Get a paginated list of L1 subnets with registry metadata",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - Subnets"
                ],
                "summary": "List L1s",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/pchain/tx-types": {
            "get": {
                "description": "Get a list of P-Chain transaction types with counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - P-Chain"
                ],
                "summary": "List P-Chain transaction types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/pchain/txs": {
            "get": {
                "description": "Get a paginated list of P-Chain transactions with optional filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - P-Chain"
                ],
                "summary": "List P-Chain transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by transaction type",
                        "name": "tx_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by subnet ID",
                        "name": "subnet_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.PChainTx"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/pchain/txs/{txId}": {
            "get": {
                "description": "Get details for a specific P-Chain transaction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - P-Chain"
                ],
                "summary": "Get P-Chain transaction by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.PChainTx"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/subnets": {
            "get": {
                "description": "Get a paginated list of subnets with optional type filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - Subnets"
                ],
                "summary": "List subnets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by subnet type (regular, elastic, l1)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Subnet"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/subnets/{subnetId}": {
            "get": {
                "description": "Get full details for a subnet including chains and registry info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - Subnets"
                ],
                "summary": "Get subnet by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subnet ID",
                        "name": "subnetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.SubnetDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/validators": {
            "get": {
                "description": "Get a paginated list of L1 validators with optional filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - Validators"
                ],
                "summary": "List validators",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by subnet ID",
                        "name": "subnet_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by active status (true/false)",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Validator"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/validators/{id}": {
            "get": {
                "description": "Get details for a specific validator by validation ID or node ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - Validators"
                ],
                "summary": "Get validator by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validation ID or Node ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.Validator"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/data/validators/{id}/deposits": {
            "get": {
                "description": "Get balance transactions (deposits, topups, refunds) for a validator",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data - Validators"
                ],
                "summary": "Get validator deposits",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Validation ID or Node ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.ValidatorDeposit"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/evm/{chainId}/stats": {
            "get": {
                "description": "Get aggregate statistics (block count, tx count, gas usage) for a chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics - Chain"
                ],
                "summary": "Get chain statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.ChainMetrics"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/evm/{chainId}/timeseries": {
            "get": {
                "description": "Get a list of available time series metrics for a chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics - Chain"
                ],
                "summary": "List available metrics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.AvailableMetric"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/evm/{chainId}/timeseries/{metric}": {
            "get": {
                "description": "Get time series data for a specific metric with configurable granularity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics - Chain"
                ],
                "summary": "Get metric time series",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chain ID",
                        "name": "chainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metric name (e.g., tx_count, gas_used)",
                        "name": "metric",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "day",
                        "description": "Time granularity (hour, day, week, month)",
                        "name": "granularity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (date, RFC3339, or unix timestamp)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (date, RFC3339, or unix timestamp)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Number of data points (max 1000)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.MetricSeries"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/fees": {
            "get": {
                "description": "Get aggregated fee statistics for L1 validators",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics - Fees"
                ],
                "summary": "Get L1 fee statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by subnet ID",
                        "name": "subnet_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of results (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.FeeStats"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/api.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/indexer/status": {
            "get": {
                "description": "Get sync status for all indexed chains",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics - Indexer"
                ],
                "summary": "Get indexer status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.IndexerStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check API server and database connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Healthy",
                        "schema": {
                            "$ref": "#/definitions/api.HealthStatus"
                        }
                    },
                    "503": {
                        "description": "Unhealthy",
                        "schema": {
                            "$ref": "#/definitions/api.HealthStatus"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/api.ErrorCode"
                },
                "details": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.FieldError"
                    }
                },
                "message": {
                    "type": "string"
                },
                "retry_after": {
                    "type": "integer"
                }
            }
        },
        "api.AvailableMetric": {
            "type": "object",
            "properties": {
                "data_points": {
                    "type": "integer",
                    "example": 365
                },
                "granularities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "hour",
                        "day",
                        "week"
                    ]
                },
                "latest_period": {
                    "type": "string"
                },
                "metric_name": {
                    "type": "string",
                    "example": "tx_count"
                }
            }
        },
        "api.Block": {
            "type": "object",
            "properties": {
                "base_fee_per_gas": {
                    "type": "integer",
                    "example": 25000000000
                },
                "block_number": {
                    "type": "integer",
                    "example": 12345678
                },
                "block_time": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer",
                    "example": 43114
                },
                "gas_limit": {
                    "type": "integer",
                    "example": 8000000
                },
                "gas_used": {
                    "type": "integer",
                    "example": 500000
                },
                "hash": {
                    "type": "string",
                    "example": "0x1234..."
                },
                "miner": {
                    "type": "string",
                    "example": "0x742d35Cc6634C0532925a3b844Bc9e7595f..."
                },
                "parent_hash": {
                    "type": "string",
                    "example": "0xabcd..."
                },
                "size": {
                    "type": "integer",
                    "example": 1024
                },
                "tx_count": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "api.ChainMetrics": {
            "type": "object",
            "properties": {
                "avg_block_time_seconds": {
                    "type": "number",
                    "example": 2
                },
                "avg_gas_used": {
                    "type": "number",
                    "example": 500000
                },
                "chain_id": {
                    "type": "integer",
                    "example": 43114
                },
                "chain_name": {
                    "type": "string",
                    "example": "C-Chain"
                },
                "last_block_time": {
                    "type": "string"
                },
                "latest_block": {
                    "type": "integer",
                    "example": 12345678
                },
                "total_blocks": {
                    "type": "integer",
                    "example": 12345678
                },
                "total_gas_used": {
                    "type": "integer",
                    "example": 50000000000000
                },
                "total_txs": {
                    "type": "integer",
                    "example": 100000000
                }
            }
        },
        "api.EVMChainStatus": {
            "type": "object",
            "properties": {
                "blocks_behind": {
                    "type": "integer",
                    "example": 22
                },
                "chain_id": {
                    "type": "integer",
                    "example": 43114
                },
                "current_block": {
                    "type": "integer",
                    "example": 12345678
                },
                "is_synced": {
                    "type": "boolean",
                    "example": true
                },
                "last_sync": {
                    "type": "string"
                },
                "latest_block": {
                    "type": "integer",
                    "example": 12345700
                },
                "name": {
                    "type": "string",
                    "example": "C-Chain"
                }
            }
        },
        "api.ErrorCode": {
            "type": "string",
            "enum": [
                "INVALID_PARAMETER",
                "NOT_FOUND",
                "INTERNAL_ERROR",
                "RATE_LIMITED",
                "VALIDATION_FAILED",
                "DATABASE_ERROR"
            ],
            "x-enum-varnames": [
                "ErrInvalidParameter",
                "ErrNotFound",
                "ErrInternalError",
                "ErrRateLimited",
                "ErrValidationFailed",
                "ErrDatabaseError"
            ]
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.APIError"
                }
            }
        },
        "api.FeeStats": {
            "type": "object",
            "properties": {
                "current_balance": {
                    "type": "integer",
                    "example": 85000000000
                },
                "deposit_tx_count": {
                    "type": "integer",
                    "example": 15
                },
                "initial_deposits": {
                    "type": "integer",
                    "example": 80000000000
                },
                "subnet_id": {
                    "type": "string",
                    "example": "2XDnKyAEr..."
                },
                "top_up_deposits": {
                    "type": "integer",
                    "example": 20000000000
                },
                "total_deposited": {
                    "type": "integer",
                    "example": 100000000000
                },
                "total_fees_paid": {
                    "type": "integer",
                    "example": 5000000000
                },
                "total_refunded": {
                    "type": "integer",
                    "example": 10000000000
                },
                "validator_count": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "api.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.HealthStatus": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "connected"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "api.IndexerStatus": {
            "type": "object",
            "properties": {
                "evm": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.EVMChainStatus"
                    }
                },
                "healthy": {
                    "type": "boolean",
                    "example": true
                },
                "last_update": {
                    "type": "string"
                },
                "pchain": {
                    "$ref": "#/definitions/api.PChainStatus"
                }
            }
        },
        "api.L1Registry": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "A high-performance L1"
                },
                "logo_url": {
                    "type": "string",
                    "example": "https://example.com/logo.png"
                },
                "name": {
                    "type": "string",
                    "example": "My L1"
                },
                "subnet_id": {
                    "type": "string",
                    "example": "2XDnKyAEr..."
                },
                "website_url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "api.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.MetricDataPoint": {
            "type": "object",
            "properties": {
                "period": {
                    "type": "string"
                },
                "value": {
                    "type": "integer",
                    "example": 1234567
                }
            }
        },
        "api.MetricSeries": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer",
                    "example": 43114
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.MetricDataPoint"
                    }
                },
                "granularity": {
                    "type": "string",
                    "example": "day"
                },
                "metric_name": {
                    "type": "string",
                    "example": "tx_count"
                }
            }
        },
        "api.PChainStatus": {
            "type": "object",
            "properties": {
                "blocks_behind": {
                    "type": "integer",
                    "example": 59
                },
                "current_block": {
                    "type": "integer",
                    "example": 24160141
                },
                "is_synced": {
                    "type": "boolean",
                    "example": true
                },
                "last_sync": {
                    "type": "string"
                },
                "latest_block": {
                    "type": "integer",
                    "example": 24160200
                }
            }
        },
        "api.PChainTx": {
            "type": "object",
            "properties": {
                "block_number": {
                    "type": "integer",
                    "example": 12345678
                },
                "block_time": {
                    "type": "string"
                },
                "tx_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "tx_id": {
                    "type": "string",
                    "example": "2ZW6HUePB..."
                },
                "tx_type": {
                    "type": "string",
                    "example": "ConvertSubnetToL1Tx"
                }
            }
        },
        "api.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/api.Meta"
                }
            }
        },
        "api.Subnet": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "example": "2q9e4r6Mu..."
                },
                "converted_block": {
                    "type": "integer",
                    "example": 12345700
                },
                "converted_time": {
                    "type": "string"
                },
                "created_block": {
                    "type": "integer",
                    "example": 12345678
                },
                "created_time": {
                    "type": "string"
                },
                "subnet_id": {
                    "type": "string",
                    "example": "2XDnKyAEr..."
                },
                "subnet_type": {
                    "type": "string",
                    "example": "l1"
                }
            }
        },
        "api.SubnetChain": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "example": "2q9e4r6Mu..."
                },
                "chain_name": {
                    "type": "string",
                    "example": "My Chain"
                },
                "created_block": {
                    "type": "integer",
                    "example": 12345678
                },
                "created_time": {
                    "type": "string"
                },
                "subnet_id": {
                    "type": "string",
                    "example": "2XDnKyAEr..."
                },
                "vm_id": {
                    "type": "string",
                    "example": "subnetevm"
                }
            }
        },
        "api.SubnetDetail": {
            "type": "object",
            "properties": {
                "chains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SubnetChain"
                    }
                },
                "registry": {
                    "$ref": "#/definitions/api.L1Registry"
                },
                "subnet": {
                    "$ref": "#/definitions/api.Subnet"
                }
            }
        },
        "api.Transaction": {
            "type": "object",
            "properties": {
                "block_number": {
                    "type": "integer",
                    "example": 12345678
                },
                "block_time": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer",
                    "example": 43114
                },
                "from": {
                    "type": "string",
                    "example": "0x742d35Cc6634C0532925a3b844Bc9e7595f..."
                },
                "gas_limit": {
                    "type": "integer",
                    "example": 21000
                },
                "gas_price": {
                    "type": "integer",
                    "example": 25000000000
                },
                "gas_used": {
                    "type": "integer",
                    "example": 21000
                },
                "hash": {
                    "type": "string",
                    "example": "0x1234..."
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "to": {
                    "description": "null for contract creation",
                    "type": "string",
                    "example": "0x123..."
                },
                "transaction_index": {
                    "type": "integer",
                    "example": 0
                },
                "type": {
                    "type": "integer",
                    "example": 2
                },
                "value": {
                    "type": "string",
                    "example": "1000000000000000000"
                }
            }
        },
        "api.Validator": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "balance": {
                    "type": "integer",
                    "example": 100000000000
                },
                "end_time": {
                    "type": "string"
                },
                "fees_paid": {
                    "type": "integer",
                    "example": 5000000000
                },
                "initial_deposit": {
                    "type": "integer",
                    "example": 100000000000
                },
                "node_id": {
                    "type": "string",
                    "example": "NodeID-P7oB2McjBGgW..."
                },
                "refund_amount": {
                    "type": "integer",
                    "example": 0
                },
                "start_time": {
                    "type": "string"
                },
                "subnet_id": {
                    "type": "string",
                    "example": "2XDnKyAEr..."
                },
                "total_topups": {
                    "type": "integer",
                    "example": 50000000000
                },
                "uptime_percentage": {
                    "type": "number",
                    "example": 99.5
                },
                "validation_id": {
                    "type": "string",
                    "example": "2ZW6HUePB..."
                },
                "weight": {
                    "type": "integer",
                    "example": 2000
                }
            }
        },
        "api.ValidatorDeposit": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 10000000000
                },
                "block_number": {
                    "type": "integer",
                    "example": 12345678
                },
                "block_time": {
                    "type": "string"
                },
                "tx_id": {
                    "type": "string",
                    "example": "2ZW6HUePB..."
                },
                "tx_type": {
                    "type": "string",
                    "example": "IncreaseL1ValidatorBalanceTx"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Health check endpoints",
            "name": "Health"
        },
        {
            "description": "EVM blockchain data (blocks, transactions)",
            "name": "Data - EVM"
        },
        {
            "description": "P-Chain transaction data",
            "name": "Data - P-Chain"
        },
        {
            "description": "Subnet and L1 information",
            "name": "Data - Subnets"
        },
        {
            "description": "L1 validator information",
            "name": "Data - Validators"
        },
        {
            "description": "L1 validation fee statistics",
            "name": "Metrics - Fees"
        },
        {
            "description": "EVM chain statistics and time series",
            "name": "Metrics - Chain"
        },
        {
            "description": "Indexer sync status",
            "name": "Metrics - Indexer"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Icicle API",
	Description:      "Avalanche P-Chain and EVM Indexer API\n\n## Overview\nThis API provides access to indexed Avalanche blockchain data including:\n- **Data API** (`/api/v1/data/*`): Blocks, transactions, subnets, validators, P-chain data\n- **Metrics API** (`/api/v1/metrics/*`): Fee statistics, chain metrics, time series data\n\n## Rate Limiting\nAll endpoints are rate limited to 60 requests/minute per IP with a burst of 10.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
